
from utils.new_api_utils import run_api, get_signature
from generator.input_generators import get_abstract_input

generated_inputs = dict()

import tensorflow as tf
import numpy as np
import copy

def get_quantized_relu_inputs():
    """
    Generates a list of valid inputs for the tf.raw_ops.QuantizedRelu operation.
    This function resolves the `InvalidArgumentError` by providing correctly typed
    quantized tensors. These are generated by using `tf.quantization.quantize`
    on standard float tensors. The resulting `features` tensor has a quantized
    dtype (e.g., tf.qint8), which is required by the operation.
    """
    list_of_inputs = []

    def create_quantized_input(float_features, min_range, max_range, q_dtype, out_dtype, name):
        """
        Helper to quantize float inputs and create a valid input dictionary.
        """
        float_tensor = tf.constant(float_features, dtype=tf.float32)
        
        quantized_tensor, q_min, q_max = tf.quantization.quantize(
            float_tensor, min_range, max_range, T=q_dtype
        )

        input_dict = {
            'features': quantized_tensor,
            'min_features': q_min,
            'max_features': q_max,
            'out_type': out_dtype,
            'name': name
        }
        return input_dict

    # Input 1: Basic case with qint8 features
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-10., -5., 0., 5., 10.], dtype=np.float32),
        min_range=-10.0, max_range=10.0, q_dtype=tf.qint8, out_dtype=tf.qint8,
        name="valid_qint8"
    )))

    # Input 2: Basic case with quint8 features
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([0., 10., 20., 30., 40.], dtype=np.float32),
        min_range=0.0, max_range=40.0, q_dtype=tf.quint8, out_dtype=tf.quint8,
        name="valid_quint8"
    )))

    # Input 3: Basic case with qint16 features
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-1000., 0., 1000.], dtype=np.float32),
        min_range=-1000.0, max_range=1000.0, q_dtype=tf.qint16, out_dtype=tf.qint16,
        name="valid_qint16"
    )))

    # Input 4: Basic case with quint16 features
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([0, 1000, 30000, 65535], dtype=np.float32),
        min_range=0.0, max_range=65535.0, q_dtype=tf.quint16, out_dtype=tf.quint16,
        name="valid_quint16"
    )))

    # Input 5: Basic case with qint32 features
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-2e9, 0, 2e9], dtype=np.float32),
        min_range=-2e9, max_range=2e9, q_dtype=tf.qint32, out_dtype=tf.qint32,
        name="valid_qint32"
    )))

    # Input 6: 2D tensor
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([[-1., 0.], [1., 2.]], dtype=np.float32),
        min_range=-2.0, max_range=2.0, q_dtype=tf.qint8, out_dtype=tf.qint8,
        name="valid_2d_qint8"
    )))

    # Input 7: All negative float inputs (should be clipped to 0)
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-10., -8., -5., -2., -0.1], dtype=np.float32),
        min_range=-10.0, max_range=10.0, q_dtype=tf.qint8, out_dtype=tf.qint8,
        name="all_negative_float_inputs"
    )))

    # Input 8: Type promotion in output
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-1., 0., 1.], dtype=np.float32),
        min_range=-1.0, max_range=1.0, q_dtype=tf.qint8, out_dtype=tf.qint16,
        name="promote_qint8_to_qint16"
    )))

    # Input 9: Asymmetric quantization range
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.array([-5., 0., 10.], dtype=np.float32),
        min_range=-5.0, max_range=10.0, q_dtype=tf.qint8, out_dtype=tf.qint8,
        name="asymmetric_range"
    )))

    # Input 10: 3D tensor
    list_of_inputs.append(copy.deepcopy(create_quantized_input(
        float_features=np.random.uniform(-5, 5, (2, 3, 2)).astype(np.float32),
        min_range=-5.0, max_range=5.0, q_dtype=tf.qint8, out_dtype=tf.qint8,
        name="valid_3d_qint8"
    )))
    
    return list_of_inputs

generated_inputs["tf.raw_ops.QuantizedRelu"] = get_quantized_relu_inputs()

def check_valid(api, list_of_inputs, lib="tf", suffix=0):
    for idx, input_dict in enumerate(list_of_inputs):
        _ = get_abstract_input(input_dict, get_signature(api, lib=lib, suffix=suffix))
        output = run_api(api, input_dict, cpu=True, lib=lib)
    
    if len(list_of_inputs) == 0:
        raise Exception("No inputs were generated for the API. Please check the input generation code.")

    print("Valid")

if 'tf.raw_ops.QuantizedRelu' not in generated_inputs:
    raise Exception("Output of the input generating function was not assigned to the generated_inputs dictionary to the key 'tf.raw_ops.QuantizedRelu'.")

check_valid('tf.raw_ops.QuantizedRelu', generated_inputs['tf.raw_ops.QuantizedRelu'], lib="tf", suffix=0)
