tf.sparse.eye,1,rule_105,num_columns
tf.sparse.eye,1,rule_105,num_rows
tf.sparse.eye,1,rule_109,num_columns
tf.sparse.eye,1,rule_109,num_rows
tf.sparse.eye,1,rule_113,num_columns
tf.sparse.eye,1,rule_113,num_rows
tf.sparse.eye,1,rule_128,num_columns
tf.sparse.eye,1,rule_128,num_rows
tf.sparse.eye,1,rule_146,num_columns
tf.sparse.eye,1,rule_146,num_rows
tf.sparse.eye,1,rule_18,num_columns
tf.sparse.eye,1,rule_18,num_rows
tf.sparse.eye,1,rule_2,num_columns
tf.sparse.eye,1,rule_2,num_rows
tf.sparse.eye,1,rule_24,num_columns
tf.sparse.eye,1,rule_38,num_columns
tf.sparse.eye,1,rule_38,num_rows
tf.sparse.eye,1,rule_42,num_rows
tf.sparse.eye,1,rule_43,num_columns
tf.sparse.eye,1,rule_48,num_columns
tf.sparse.eye,1,rule_48,num_rows
tf.sparse.eye,1,rule_5,num_columns
tf.sparse.eye,1,rule_5,num_rows
tf.sparse.eye,1,rule_59,num_columns
tf.sparse.eye,1,rule_59,num_rows
tf.sparse.eye,1,rule_6,num_columns
tf.sparse.eye,1,rule_6,num_rows
tf.sparse.eye,1,rule_63,num_rows
tf.sparse.eye,1,rule_68,num_columns
tf.sparse.eye,1,rule_68,num_rows
tf.sparse.eye,1,rule_73,num_columns
tf.sparse.eye,1,rule_73,num_rows
tf.sparse.eye,2,rule_1,num_rows,num_columns
tf.sparse.eye,2,rule_17,num_rows,num_columns
tf.sparse.eye,2,rule_31,num_rows,num_columns
tf.sparse.eye,2,rule_33,num_rows,num_columns
tf.sparse.eye,2,rule_45,num_rows,num_columns
tf.sparse.eye,2,rule_51,num_rows,num_columns
tf.sparse.eye,2,rule_60,num_rows,num_columns
tf.sparse.eye,2,rule_70,num_rows,num_columns
tf.sparse.eye,2,rule_78,num_rows,num_columns
