tf.sparse.eye,1,rule_105,num_rows
tf.sparse.eye,1,rule_113,num_columns
tf.sparse.eye,1,rule_113,num_rows
tf.sparse.eye,1,rule_128,num_columns
tf.sparse.eye,1,rule_128,num_rows
tf.sparse.eye,1,rule_146,num_columns
tf.sparse.eye,1,rule_2,num_rows
tf.sparse.eye,1,rule_24,num_rows
tf.sparse.eye,1,rule_38,num_columns
tf.sparse.eye,1,rule_42,num_rows
tf.sparse.eye,1,rule_43,num_columns
tf.sparse.eye,1,rule_43,num_rows
tf.sparse.eye,1,rule_48,num_columns
tf.sparse.eye,1,rule_48,num_rows
tf.sparse.eye,1,rule_49,num_rows
tf.sparse.eye,1,rule_5,num_columns
tf.sparse.eye,1,rule_59,num_columns
tf.sparse.eye,1,rule_59,num_rows
tf.sparse.eye,1,rule_6,num_columns
tf.sparse.eye,1,rule_6,num_rows
tf.sparse.eye,1,rule_63,num_columns
tf.sparse.eye,1,rule_63,num_rows
tf.sparse.eye,1,rule_73,num_rows
tf.sparse.eye,2,rule_1,num_rows,num_columns
tf.sparse.eye,2,rule_45,num_rows,num_columns
tf.sparse.eye,2,rule_51,num_rows,num_columns
tf.sparse.eye,2,rule_7,num_rows,num_columns
tf.sparse.eye,2,rule_78,num_rows,num_columns
