torch.polar,1,rule_15,abs
torch.polar,1,rule_15,angle
torch.polar,1,rule_16,abs
torch.polar,1,rule_16,angle
torch.polar,1,rule_19,abs
torch.polar,1,rule_19,angle
torch.polar,1,rule_2,abs
torch.polar,1,rule_2,angle
torch.polar,2,rule_1,abs,angle
torch.polar,2,rule_17,abs,angle
torch.polar,2,rule_18,abs,angle
torch.polar,2,rule_26,abs,angle
torch.polar,2,rule_33,abs,angle
torch.polar,2,rule_37,abs,angle
torch.polar,2,rule_42,abs,angle
torch.polar,2,rule_45,abs,angle
torch.polar,2,rule_46,abs,angle
torch.polar,2,rule_50,abs,angle
torch.polar,2,rule_56,abs,angle
torch.polar,2,rule_58,abs,angle
torch.polar,2,rule_61,abs,angle
torch.polar,2,rule_62,abs,angle
torch.polar,2,rule_64,abs,angle
torch.polar,2,rule_75,abs,angle
torch.polar,2,rule_76,abs,angle
torch.polar,2,rule_90,abs,angle
torch.polar,2,rule_99,abs,angle
